import { Experience } from "~@types/api";

export const experiences: Experience[] = [
  {
    title: "Dashlane",
    when: "2021 - 2022",
    website: "https://www.dashlane.com/",
    websiteDisplay: "dashlane.com",
    role: "Fullstack JS",
    description: "dashlane.description",
    environment: "React, Typescript, GraphQL, GraphCMS, Kanban, A/B tests",
    image: "logo-dashlane.png",
  },
  {
    title: "Levio",
    when: "2021 (4 months)",
    website: "https://levio.ca/",
    websiteDisplay: "levio.ca",
    role: "Fullstack JS",
    description: "levio.description",
    environment: "React, Typescript, SCRUM",
    image: "logo-levio.png",
  },
  {
    title: "Premier Octet",
    when: "2020 - 2021",
    website: "https://www.premieroctet.com/",
    websiteDisplay: "premieroctet.com",
    role: "Fullstack JS",
    description: "premieroctet.description",
    environment: "React, NextJS, NestJS, React Native, PostgreSQL, Typescript",
    image: "logo-premieroctet.png",
  },
  {
    title: "Sewan",
    when: "2018 - 2020",
    website: "http://www.sewan.fr",
    websiteDisplay: "sewan.fr",
    role: "Fullstack JS",
    description: "sewan.description",
    environment: "React, MongoDB, NodeJS, GraphQL, Scrum",
    image: "logo-sewan.png",
  },
  {
    title: "Neftis",
    when: "2017 - 2018",
    website: "http://www.neftis.fr",
    websiteDisplay: "neftis.fr",
    role: "Fullstack",
    description: "neftis.description",
    environment: "PHP, jQuery, MySQL, Flexit",
    image: "logo-neftis.png",
    imageProps: {
      width: "130px",
    },
  },
  {
    title: "GEN Contact",
    when: "2015 - 2017",
    website: "http://www.gencontact.fr",
    websiteDisplay: "gencontact.fr",
    role: "Fullstack",
    description: "gencontact.description",
    environment: "PHP, jQuery, MySQL, Photoshop",
    image: "logo-gen-contact.png",
  },
];
