export const projects = [
  {
    logo: "/assets/projets/studiod-visuel.png",
    bg: "/assets/projets/studiod-fond.jpg",
    title: "Studio D",
    description: `studiod.description`,
    role: "Fullstack JS",
    context: "freelance",
    stack: "React, NextJS, Strapi",
    link: "https://www.studiod-danse.fr/",
  },
  {
    logo: "/assets/projets/digestclub-visuel.svg",
    bg: "/assets/projets/digestclub-fond.jpg",
    title: "Digest.Club",
    description: `digestclub.description`,
    role: "Fullstack JS",
    context: "pro",
    stack: "React, NextJS, NestJS",
    link: "https://digest.club/",
  },
  {
    logo: "/assets/projets/jikiki-logo.svg",
    bg: "/assets/projets/jikiki-fond.jpg",
    title: "Jikiki",
    description: `jikiki.description`,
    role: "Fullstack JS",
    context: "freelance",
    stack: "React, NextJS, Strapi",
    link: "https://jikiki.vercel.app/",
  },
  {
    logo: "/assets/projets/materalia-visuel.png",
    bg: "/assets/projets/materalia-fond.jpg",
    title: "Materalia",
    description: `materalia.description`,
    role: "Fullstack",
    context: "pro",
    stack: "PHP/jQuery",
    link: "https://www.materalia.fr/",
  },
  {
    logo: "/assets/projets/creutzwald-visuel.png",
    bg: "/assets/projets/creutzwald-fond.jpg",
    title: "Creutzwald",
    description: `creutzwald.description`,
    role: "Fullstack",
    context: "pro",
    stack: "PHP/jQuery",
    link: "https://www.creutzwald.fr/",
  },
  {
    logo: "/assets/projets/ysheza-visuel.png",
    bg: "/assets/projets/ysheza-fond.jpg",
    title: "Yshéza",
    description: `ysheza.description`,
    role: "Fullstack",
    context: "freelance",
    stack: "Symfony",
    link: "http://ysheza.fr/",
  },
  // {
  //   logo: "/assets/projets/creative-drawer-visuel.png",
  //   bg: "/assets/projets/creative-drawer-fond.jpg",
  //   title: "Créative Drawer",
  //   description: `Creative Drawer is an open source CMS targeting designers with
  //   no computer skills, so that they can easily share their
  //   creations on a dedicated personal space.`,
  //   role: "Fullstack",
  //   context: "w/ friends",
  //   stack: "PHP/jQuery",
  //   link: "http://www.creative-drawer.ovh/landing",
  // },
  // {
  //   logo: "/assets/projets/premium-decorations-visuel.png",
  //   bg: "/assets/projets/premium-decorations-fond.jpg",
  //   title: "Premium Décorations",
  //   description: `Contemporary interior design company specializing in
  //   decoration advice, virtual interior design and home staging.`,
  //   role: "Fullstack",
  //   context: "Professional",
  //   stack: "PHP/jQuery",
  //   link: "http://www.premium-decorations.com/",
  // },
];
